### ISSUE TITLE
sparse is not passed in __init__ function of StableEmbedding

### ISSUE THREAD

**Issue by SirRob1997** [facebookresearch/bitsandbytes#11]
In [this line](https://github.com/facebookresearch/bitsandbytes/blob/main/bitsandbytes/nn/modules.py#L19) instead of passing the `sparse` parameter, `False` is passed. Is this intended? It's a little confusing since the default for `sparse` is `True` here but `False` in `torch.nn.Embedding`

**Comment by TimDettmers** [comment]
Good catch! Thank you for reporting this! I will fix this with the next release. Feel free to create a pull request!
