### ISSUE TITLE
python setup.py install error

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/bitsandbytes#18]
(bitsandbytes) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/bitsandbytes$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    name = f"bitsandbytes-cuda{os.environ['CUDA_VERSION']}",
  File "/home/chenxin/disk1/anaconda3/envs/bitsandbytes/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VERSION'
(bitsandbytes) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/bitsandbytes$ conda list | grep cudatoolkit
cudatoolkit               11.1.1               h6406543_8    conda-forge

**Comment by TimDettmers** [comment]
Sorry, this is currently not well documented and a bit finicky. What you have to do to install is set the `CUDA_VERSION` variable, for example like this: `CUDA_VERSION=113 python setup.py install`.

**Comment by mathpopo** [comment]
@TimDettmers  thanks
(bitsandbytes) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/bitsandbytes$ CUDA_VERSION=111 python setup.py install
running install
running bdist_egg
running egg_info
creating bitsandbytes_cuda111.egg-info
writing bitsandbytes_cuda111.egg-info/PKG-INFO
writing dependency_links to bitsandbytes_cuda111.egg-info/dependency_links.txt
writing top-level names to bitsandbytes_cuda111.egg-info/top_level.txt
writing manifest file 'bitsandbytes_cuda111.egg-info/SOURCES.txt'
reading manifest file 'bitsandbytes_cuda111.egg-info/SOURCES.txt'
adding license file 'LICENSE'
adding license file 'NOTICE.md'
writing manifest file 'bitsandbytes_cuda111.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/bitsandbytes
copying bitsandbytes/functional.py -> build/lib/bitsandbytes
copying bitsandbytes/__init__.py -> build/lib/bitsandbytes
creating build/lib/bitsandbytes/nn
copying bitsandbytes/nn/modules.py -> build/lib/bitsandbytes/nn
copying bitsandbytes/nn/__init__.py -> build/lib/bitsandbytes/nn
creating build/lib/bitsandbytes/optim
copying bitsandbytes/optim/adam.py -> build/lib/bitsandbytes/optim
copying bitsandbytes/optim/lamb.py -> build/lib/bitsandbytes/optim
copying bitsandbytes/optim/lars.py -> build/lib/bitsandbytes/optim
copying bitsandbytes/optim/optimizer.py -> build/lib/bitsandbytes/optim
copying bitsandbytes/optim/rmsprop.py -> build/lib/bitsandbytes/optim
copying bitsandbytes/optim/sgd.py -> build/lib/bitsandbytes/optim
copying bitsandbytes/optim/__init__.py -> build/lib/bitsandbytes/optim
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/bitsandbytes
copying build/lib/bitsandbytes/functional.py -> build/bdist.linux-x86_64/egg/bitsandbytes
creating build/bdist.linux-x86_64/egg/bitsandbytes/nn
copying build/lib/bitsandbytes/nn/modules.py -> build/bdist.linux-x86_64/egg/bitsandbytes/nn
copying build/lib/bitsandbytes/nn/__init__.py -> build/bdist.linux-x86_64/egg/bitsandbytes/nn
creating build/bdist.linux-x86_64/egg/bitsandbytes/optim
copying build/lib/bitsandbytes/optim/adam.py -> build/bdist.linux-x86_64/egg/bitsandbytes/optim
copying build/lib/bitsandbytes/optim/lamb.py -> build/bdist.linux-x86_64/egg/bitsandbytes/optim
copying build/lib/bitsandbytes/optim/lars.py -> build/bdist.linux-x86_64/egg/bitsandbytes/optim
copying build/lib/bitsandbytes/optim/optimizer.py -> build/bdist.linux-x86_64/egg/bitsandbytes/optim
copying build/lib/bitsandbytes/optim/rmsprop.py -> build/bdist.linux-x86_64/egg/bitsandbytes/optim
copying build/lib/bitsandbytes/optim/sgd.py -> build/bdist.linux-x86_64/egg/bitsandbytes/optim
copying build/lib/bitsandbytes/optim/__init__.py -> build/bdist.linux-x86_64/egg/bitsandbytes/optim
copying build/lib/bitsandbytes/__init__.py -> build/bdist.linux-x86_64/egg/bitsandbytes
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/functional.py to functional.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/nn/modules.py to modules.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/nn/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/adam.py to adam.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/lamb.py to lamb.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/lars.py to lars.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/optimizer.py to optimizer.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/rmsprop.py to rmsprop.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/sgd.py to sgd.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/optim/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/bitsandbytes/__init__.py to __init__.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes_cuda111.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes_cuda111.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes_cuda111.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bitsandbytes_cuda111.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
bitsandbytes.__pycache__.functional.cpython-38: module references __file__
creating dist
creating 'dist/bitsandbytes_cuda111-0.25.0-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing bitsandbytes_cuda111-0.25.0-py3.8.egg
creating /home/chenxin/disk1/anaconda3/envs/bitsandbytes/lib/python3.8/site-packages/bitsandbytes_cuda111-0.25.0-py3.8.egg
Extracting bitsandbytes_cuda111-0.25.0-py3.8.egg to /home/chenxin/disk1/anaconda3/envs/bitsandbytes/lib/python3.8/site-packages
Adding bitsandbytes-cuda111 0.25.0 to easy-install.pth file

Installed /home/chenxin/disk1/anaconda3/envs/bitsandbytes/lib/python3.8/site-packages/bitsandbytes_cuda111-0.25.0-py3.8.egg
Processing dependencies for bitsandbytes-cuda111==0.25.0
Finished processing dependencies for bitsandbytes-cuda111==0.25.0
(bitsandbytes) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/bitsandbytes$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
(bitsandbytes) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/bitsandbytes$

**Comment by mathpopo** [comment]
@TimDettmers 

(bitsandbytes) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/bitsandbytes$ python ./check_bnb_install.py 
Traceback (most recent call last):
  File "./check_bnb_install.py", line 1, in <module>
    import bitsandbytes as bnb
  File "/home/chenxin/disk1/github/bitsandbytes/bitsandbytes/__init__.py", line 5, in <module>
    from .optim import adam
  File "/home/chenxin/disk1/github/bitsandbytes/bitsandbytes/optim/__init__.py", line 5, in <module>
    from .adam import Adam, Adam8bit, Adam32bit
  File "/home/chenxin/disk1/github/bitsandbytes/bitsandbytes/optim/adam.py", line 11, in <module>
    from bitsandbytes.optim.optimizer import Optimizer2State
  File "/home/chenxin/disk1/github/bitsandbytes/bitsandbytes/optim/optimizer.py", line 6, in <module>
    import bitsandbytes.functional as F
  File "/home/chenxin/disk1/github/bitsandbytes/bitsandbytes/functional.py", line 13, in <module>
    lib = ct.cdll.LoadLibrary(os.path.dirname(__file__) + '/libbitsandbytes.so')
  File "/home/chenxin/disk1/anaconda3/envs/bitsandbytes/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/home/chenxin/disk1/anaconda3/envs/bitsandbytes/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/chenxin/disk1/github/bitsandbytes/bitsandbytes/libbitsandbytes.so: cannot open shared object file: No such file or directory

**Comment by mathpopo** [comment]
@TimDettmers  but i download all

**Comment by TimDettmers** [comment]
Sorry that this is all a bit unintuitive. I did not have the time yet to document this. By default, currently, there is no compilation step when you install via `python setup.py install`. So an additional step to get the library working is to compile from source. Please have a look [here](https://github.com/facebookresearch/bitsandbytes/blob/main/compile_from_source.md) for instructions to compile from source.

**Comment by mathpopo** [comment]
@TimDettmers  ok
(bitsandbytes) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/bitsandbytes$ python check_bnb_install.py
SUCCESS!
Installation was successful!

**Comment by mathpopo** [comment]
1535  make cuda11x
 1536  CUDA_VERSION=11x python setup.py install
 1537  python check_bnb_install.py
 1538  history

**Comment by mathpopo** [comment]
@TimDettmers Sorry , if i use g++5,say not support C++,But i see makefile include =std++11

**Comment by mathpopo** [comment]
i put nvcc compile --std==c++11,not show this ,but show as bel
![webwxgetmsgimg(5)](https://user-images.githubusercontent.com/21274466/142829898-ee160c37-cd7e-4d1b-b7e0-7d6324273f8b.png)
ow

**Comment by mathpopo** [comment]
thrust?

**Comment by xdevfaheem** [comment]
OSError: /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes.so: cannot open shared object file: 
No such file or directory

What Should I Do To Get Rid of This...
