### ISSUE TITLE
import bitsandbytes as bnb 错误

### ISSUE THREAD

**Issue by zhishui3** [facebookresearch/bitsandbytes#21]
import bitsandbytes as bnb
出现如下
OSError: /home/anaconda3/envs/ner/lib/python3.6/site-packages/bitsandbytes/libbitsandbytes.so: undefined symbol: __fatbinwrap_38_cuda_device_runtime_compute_75_cpp1_ii_8b1a5d37

您好，请问这该怎么解决啊

**Comment by mi4da** [comment]
好像是驱动问题

**Comment by liesun1994** [comment]
same error, have you solved the problem?

**Comment by Syhen** [comment]
Compile and install from source solved this problem for me.

Just following this: https://github.com/facebookresearch/bitsandbytes/blob/main/compile_from_source.md

**Comment by TimDettmers** [comment]
This error stems from a faulty installation where you have multiple CUDA versions installed where some mismatch with the supported CUDA version for your GPU. We are working on a script to debug faulty installation but as of now, the best way is to compile from source which should always work or make the version mismatch.
